create or replace FUNCTION AD_FNC_BUSCAR_PRECO_MIN_MAX(P_CODTAB IN INTEGER, P_CODPROD IN INTEGER, P_CONTROLE VARCHAR, P_CODLOCAL INT)
RETURN FLOAT
IS
  V_PRECO FLOAT;
BEGIN
/*
    Autor: Claiton Farias (Dev. Center)
    Data: Agosto/2024
    Objetivo: Função usada em Regra na Central em Java para criar evento de liberação e também usada para cálculo de comissão.
*/
  DECLARE
  P_PARAMLOCAL CHAR(1);
  P_PARAMCONTROLE CHAR(1);
 BEGIN
    P_PARAMLOCAL := GET_TSIPAR_LOGICO('CUSTOFORLOC');
    P_PARAMCONTROLE := GET_TSIPAR_LOGICO('CUSTOFORCON');

    SELECT
        COALESCE(EXC.VLRVENDA,0) AS PRECO
        INTO V_PRECO
    FROM TGFEXC EXC
        INNER JOIN TGFTAB TAB ON (TAB.CODTAB = P_CODTAB)
    WHERE EXC.NUTAB = TAB.NUTAB
        AND EXC.CODPROD = P_CODPROD
        AND EXC.CODLOCAL = CASE WHEN P_PARAMLOCAL = 'N' THEN 0 ELSE P_CODLOCAL END
        AND EXC.CONTROLE = CASE WHEN P_PARAMCONTROLE = 'N' THEN ' ' ELSE P_CONTROLE END;

     EXCEPTION WHEN NO_DATA_FOUND THEN
      V_PRECO := 0;
 END;

 RETURN (V_PRECO);
END;

